name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      CUSTOM_PROPERTY: "custom_value"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print custom property
        run: |
         echo "Custom property value: $CUSTOM_PROPERTY"
