---
name: 'update-pr-title'
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate branch name
        uses: opencepk/opencepk-module-ghactions-common/github-flow-check-branch-name@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR title to branch name
        uses: opencepk/opencepk-module-ghactions-common/github-flow-update-pr-title@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
